config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.has_role? :admin } do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_scope :user do
    get "/omniauth_callbacks/linkedin" => "omniauth_callbacks"
  end

  resources :job_listings
  resources :experiences do
    resources :ai_messages
  end

  get 'omniauth_callbacks/linkedin'

  root "application#root"
end

app/models/ai_message.rb
require "openai"

# TODO: rename to "Message"
class AiMessage < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :experience

  enum role: { user: "user", assistant: "assistant", system: "system" }, _suffix: true

  validates :role, presence: true
  validates :content, presence: true

  after_create_commit :fetch_openai_response, if: :user_role?
  after_create_commit -> { broadcast_created }
  after_update_commit -> { broadcast_updated }

  def broadcast_created
    broadcast_append_later_to(
      "#{dom_id(experience)}_ai_messages",
      partial: "ai_messages/ai_message",
      locals: { ai_message: self, scroll_to: true },
      target: "#{dom_id(experience)}_ai_messages"
    )
  end

  def broadcast_updated
    broadcast_append_to(
      "#{dom_id(experience)}_ai_messages",
      partial: "ai_messages/ai_message",
      locals: { ai_message: self, scroll_to: true },
      target: "#{dom_id(experience)}_ai_messages"
    )
  end

  broadcasts_to :experience

  scope :default_order, -> { order(created_at: :asc) }
  scope :previous_messages, -> { experience.ai_messages.where("created_at < ?", created_at) }
  scope :for_openai, -> { select(:role, :content).as_json(only: [:role, :content]) }

  def fetch_openai_response
    FetchOpenaiResponseJob.perform_later(experience)
  end
end

app/controllers/ai_messages_controller.rb
class AiMessagesController < ApplicationController
  before_action :authenticate_user!, :set_experience
  before_action :set_ai_message, only: %i[ show edit update destroy ]

  # GET /ai_messages or /ai_messages.json
  def index
    @ai_messages = @experience.ai_messages
  end

  # GET /ai_messages/1 or /ai_messages/1.json
  def show
  end

  # GET /ai_messages/new
  def new
    @ai_message =  @experience.ai_messages.new
  end

  # GET /ai_messages/1/edit
  def edit
  end

  # POST /ai_messages or /ai_messages.json
  def create
    @ai_message = @experience.ai_messages.new(ai_message_params)

    respond_to do |format|
      if @ai_message.save
        format.turbo_stream { render turbo_stream: turbo_stream.append("ai_messages", @ai_message) }
        format.html { redirect_to experience_url(@experience), notice: "Ai message was successfully created." }
        format.json { render :show, status: :created, location: @ai_message }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@ai_message, partial: "ai_messages/form", locals: { ai_message: @ai_message }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ai_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ai_messages/1 or /ai_messages/1.json
  def update
    respond_to do |format|
      if @ai_message.update(ai_message_params)
        format.html { redirect_to experience_url(@experience), notice: "Ai message was successfully updated." }
        format.json { render :show, status: :ok, location: @ai_message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ai_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ai_messages/1 or /ai_messages/1.json
  def destroy
    @ai_message.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@ai_message) }
      format.html { redirect_to experience_url(@experience), notice: "Ai message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_ai_message
    @ai_message = @experience.ai_messages.find(params[:id])
  end

  def set_experience
    @experience = current_user.experiences.find(params[:experience_id])
  end

  def ai_message_params
    params.require(:ai_message).permit(:content)
  end
end

app/helpers/ai_messages_helper.rb
module AiMessagesHelper
end

app/views/ai_messages/_ai_message.html.erb
<div id="<%= dom_id ai_message %>">
  <div class="d-flex justify-content-between align-items-center">
    <strong><%= ai_message.role %></strong>
    <%= button_to "Delete", experience_ai_message_path(ai_message.experience, ai_message),
                  method: :delete,
                  data: {
                    "turbo-method": :delete,
                    "turbo-confirm": "Are you sure you want to delete this message?" },
                  class: "btn btn-link text-danger" %>
  </div>
  <%= markdown ai_message.content %>
</div>

app/views/ai_messages/_form.html.erb
<%= form_with(model: [@experience, @ai_message],
              data: { controller: 'ai-message-form', action: 'turbo:submit-end->ai-message-form#reset' }) do |form| %>
  <div class="input-group">
    <%= form.text_area :content,
                       id: 'ai_message_content',
                       rows: 2,
                       class: "form-control",
                       placeholder: "How can I improve this description?",
                       "aria-label": "Ask AI for feedback on this experience" %>
    <%= form.submit "Send", class: "btn btn-primary",
                            'data-ai-message-form-target': 'button' %>
  </div>
  <% @ai_message.errors.each do |error| %>
    <div class="text-danger mt-2">
      <span class="help-block"><%= error.full_message %></span>
    </div>
  <% end %>
<% end %>

app/views/ai_messages/create.turbo_stream.erb
<%= turbo_stream.append "#{dom_id(@ai_message.experience)}_ai_messages" do %>
  <%= render "ai_message", ai_message: @ai_message, scroll_to: true %>
<% end %>
<%= turbo_stream.replace "new_ai_message" do %>
  <%= render "form", experience: @ai_message.experience %>
<% end %>

app/views/ai_messages/edit.html.erb
<h1>Editing ai message</h1>

<%= render "form", ai_message: @ai_message %>

<br>

<div>
  <%= link_to "Show this ai message", experience_ai_message_path(@experience, @ai_message) %> |
  <%= link_to "Back to ai messages", experience_ai_messages_path %>
</div>

app/views/ai_messages/index.html.erb
<h1>Ai messages</h1>
<div id="ai_messages">
  <% @ai_messages.each do |ai_message| %>
    <%= render ai_message %>
    <p>
      <%= link_to "Show this ai message", experience_ai_message_path(@experience, ai_message) %>
    </p>
  <% end %>
</div>

<%= link_to "New ai message", new_experience_ai_message_path(@experience) %>

app/views/ai_messages/new.html.erb
<%= turbo_frame_tag "new_ai_message" do %>
  <div class="my-3">
    <h2 class="sr-only">New ai message</h2>
    <%= render "form" %>
  </div>
<% end %>

app/views/ai_messages/show.html.erb
<%= render @ai_message %>

<div>
  <%= link_to "Edit this ai message", edit_experience_ai_message_path(@experience, @ai_message) %> |
  <%= link_to "Back to ai messages", experience_ai_messages_path %>

  <%= button_to "Destroy this ai message", experience_ai_message_path(@experience, @ai_message), method: :delete, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure? This is NOT reversible" }, class: "btn btn-danger" %>
</div>