config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.has_role? :admin } do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_scope :user do
    get "/omniauth_callbacks/linkedin" => "omniauth_callbacks"
  end

  resources :job_listings
  resources :experiences do
    resources :ai_messages
  end

  get 'omniauth_callbacks/linkedin'

  root "application#root"
end

app/views/shared/_breadcrumbs.html.erb
<% if @breadcrumbs.present? %>
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <% @breadcrumbs.each do |breadcrumb| %>
          <% if breadcrumb == @breadcrumbs.last %>
            <li class="breadcrumb-item active" aria-current="page">
              <%= breadcrumb.fetch(:content) %>
            </li>
          <% else %>
            <li class="breadcrumb-item">
              <%= link_to breadcrumb.fetch(:content), breadcrumb[:href] %>
            </li>
          <% end %>
        <% end %>
      </ol>
    </nav>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %>" role="alert">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bd-footer py-4 py-md-5 mt-5 bg-body-tertiary mt-auto">
  <div class="d-flex justify-content-center my-5">
    <ul class="list-group list-group-horizontal">
      <%# <li class="list-group-item">About</li> %>
      <li class="list-group-item">
        <%= link_to "https://github.com/BigGreenCompany/cv-boost", target: "_blank", class: "btn btn-link text-dark" do %>
          Open Source
        <% end %>
      </li>
      <%# <li class="list-group-item">Open Startup</li> %>
      <%# <li class="list-group-item">Analytics</li> %>
      <%# <li class="list-group-item">Privacy Policy</li> %>
      <%# <li class="list-group-item">Terms and Conditions</li> %>
    </ul>
  </div>
  <div class="d-flex justify-content-center my-5">
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">
        <%= link_to "https://github.com/heratyian", target: "_blank", class: "btn btn-link text-dark" do %>
          <i class="fa-brands fa-github"></i>
        <% end %>
      </li>
      <li class="list-group-item">
        <%
          email_params = {
            subject: "CV Boost Help",
            body: "👋 Please let us know how we can help you."
          }.to_param.gsub("+", "%20")
        %>
        <%= link_to "mailto:ian@biggreen.company?#{email_params}", target: "_blank", class: "btn btn-link text-dark" do %>
          <i class="fa-regular fa-envelope"></i>
        <% end %>
      </li>
    </ul>
  </div>
  <p class="text-center mt-5">© <%= Time.now.year %> Big Green Company. All rights reserved.</p>
</footer>

app/views/shared/_meta_tags.html.erb
<%= display_meta_tags(
    site: 'CV Boost',
    description: 'The perfect tool for job seekers who want to stand out from the competition and land their dream job! 🙌',
    keywords: 'job application resume cv chat gpt ai',
    og: {
      type: 'website',
      image: image_url('man-with-resumes.jpeg')
    })
%>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "CV Boost", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Experiences", experiences_path, class: "nav-link #{("active" if controller_name == 'experiences')}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Job Listings", job_listings_path, class: "nav-link #{("active" if controller_name == 'job_listings')}" %>
        </li>
        <% if current_user&.has_role? :admin %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Admin
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Admin", rails_admin_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "Blazer", blazer_path, class: "dropdown-item", target: "_blank" %>
              </li>
              <li>
                <%= link_to "Sidekiq", sidekiq_web_path, class: "dropdown-item", target: "_blank" %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
      <hr/>
      <ul class="navbar-nav">
        <% if current_user.present? %>
          <li class="nav-item d-flex">
            <%= link_to edit_user_registration_path, class: "nav-link #{("active" if current_page?(edit_user_registration_path))}" do %>
              <% if current_user.image_url.present? %>
                <img class="rounded-circle me-1" alt="user profile image" src="<%= current_user.image_url %>" style="width: 3rem">
              <% end %>
              <%= current_user.email %>
            <% end %>
          </li>
          <li class="nav-item my-auto">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link #{("active" if current_page?(new_user_session_path))}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link #{("active" if current_page?(new_user_registration_path))}" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>