config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.has_role? :admin } do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_scope :user do
    get "/omniauth_callbacks/linkedin" => "omniauth_callbacks"
  end

  resources :job_listings
  resources :experiences do
    resources :ai_messages
  end

  get 'omniauth_callbacks/linkedin'

  root "application#root"
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_paper_trail skip: [:created_at, :updated_at]

  belongs_to :user
  belongs_to :job_listing, optional: true
  has_many :ai_messages, dependent: :destroy

  broadcasts

  enum category: {
    work: "work",
    education: "education"
  }

  has_rich_text :description

  validates :started_at, presence: true
  validates :place, presence: true
  validates :title, presence: true
  validate :description_cannot_include_attachments

  def prompt
    <<~TEXT
      You are an expert at reviewing resumes for job applications.
      #{job_listing&.prompt}
      I want you to give feedback on how to improve the description of this experience.
      This experience is one of many in the #{category} experience section.
      ```html
      #{place}
      #{title}
      #{location}
      #{description}

      Please respond using markdown for rich text. No HTML.
      ```
    TEXT
  end

  def fetch_openai_response
    response = OpenAI::Client.new.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: ai_messages.for_openai.prepend({role: "system", content: prompt}),
        temperature: 0.7,
        n: 1,
        stream: stream_proc,
      }
    )
  end

  # TODO: could lead to performance issues for multiple users
  # https://gist.github.com/alexrudall/cb5ee1e109353ef358adb4e66631799d?permalink_comment_id=4711444#gistcomment-4711444
  def stream_proc
    ai_message = ai_messages.create(role: "assistant", content: "")
    proc do |chunk, _bytesize|
      new_content = chunk.dig("choices", 0, "delta", "content")
      ai_message.update(content: ai_message.content + new_content) if new_content
    end
  end

  scope :default_order, -> { order(started_at: :desc) }

  def to_s
    "#{title} at #{place}"
  end

  private

  def description_cannot_include_attachments
    if description.body.attachments.any?
      errors.add(:description, "cannot include attachments")
    end
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /experiences or /experiences.json
  def index
    @breadcrumbs = [
      {content: "Experiences", href: experiences_path},
    ]
    @experiences = current_user.experiences.all.default_order
  end

  # GET /experiences/1 or /experiences/1.json
  def show
    @breadcrumbs = [
      {content: "Experiences", href: experiences_path},
      {content: @experience.to_s}
    ]
  end

  # GET /experiences/new
  def new
    @breadcrumbs = [
      {content: "Experiences", href: experiences_path},
      {content: "New"}
    ]
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
    @breadcrumbs = [
      {content: "Experiences", href: experiences_path},
      {content: @experience.to_s, href: experience_path(@experience)},
      {content: "Edit"}
    ]
  end

  # POST /experiences or /experiences.json
  def create
    @experience = current_user.experiences.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to experience_url(@experience), notice: "Experience was successfully created." }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1 or /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to experience_url(@experience), notice: "Experience was successfully updated." }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1 or /experiences/1.json
  def destroy
    @experience.destroy

    respond_to do |format|
      format.html { redirect_to experiences_url, notice: "Experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_experience
    @experience = current_user.experiences.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:place, :title, :started_at, :ended_at, :location, :description, :category, :job_listing_id)
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_experience.html.erb
<%= turbo_frame_tag dom_id(experience) do %>
  <div id="<%= dom_id experience %>" class="card">
    <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <h1 class="me-auto mb-0 h6"><%= experience.place %></h1>
        <%= link_to edit_experience_path(experience), class: "me-2" do %>
          <i class="fa-solid fa-pen-to-square"></i>
        <% end %>
        <%= button_to experience, method: :delete, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure? This is NOT reversible" }, class: "btn btn-link" do %>
          <i class="fa-solid fa-trash text-danger"></i>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <p><%= experience.title %></p>

      <p>
        <%= experience.started_at.strftime("%B %Y") %> to <%= experience.ended_at&.strftime("%B %Y") %>
      </p>

      <p>
        <%= experience.location %>
      </p>

      <hr/>

      <p>
        <%= experience.description %>
      </p>

    </div>
    <div class="card-footer">
      <% if experience.job_listing.present? %>
        Applying for <%= link_to experience.job_listing, job_listing_path(experience.job_listing), data: { turbo: false } %>
      <% else %>
        Add a job listing to this experience for custom tailored suggestions.
      <% end %>
    </div>
  </div>
<% end %>

app/views/experiences/_form.html.erb
<%= form_with(model: experience) do |form| %>
  <% if experience.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
        <% experience.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :place, class: "form-label" %>
    <%= form.text_field :place, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :started_at, class: "form-label" %>
    <%= form.date_field :started_at, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :ended_at, class: "form-label" %>
    <%= form.date_field :ended_at, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :location, class: "form-label" %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.rich_text_area :description, id: "experience-description-rich-text-area", class: "form-control", data: { "action-text-attachment-include": false } %>
  </div>

  <div class="mb-3">
    <%= form.label :category, class: "form-label" %>
    <%= form.select :category, Experience.categories.to_a, {}, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :job_listing, class: "form-label" %>
    <%= form.select :job_listing_id, current_user.job_listings.collect {|job| [ job.to_s, job.id ] }, { include_blank: true }, class: "form-control", 'aria-describedby':"experience-job-listing-help" %>
    <div id="experience-job-listing-help" class="form-text">We'll use this job listing to generate suggestions on how to best describe this experience</small>
  </div>

  <div class="my-3">
    <%= form.submit "Save", class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<div class="container">
  <h1>Editing experience</h1>
  <%= turbo_frame_tag dom_id(@experience) do %>
    <%= render "form", experience: @experience %>
  <% end %>
</div>

app/views/experiences/index.html.erb
<div class="container">
  <div class="card">
    <div class="card-header d-flex align-items-center">
      <h1 class="me-auto h6 mb-0">Experiences</h1>
      <%= link_to new_experience_path do %>
        <i class="fa-solid fa-plus fa-lg"></i>
      <% end %>
    </div>
    <ul id="experiences" class="list-group list-group-flush">
      <% @experiences.each do |experience| %>
        <%= link_to experience, class: "list-group-item d-flex align-items-center" do %>
          <div class="me-auto">
            <div class="badge bg-light text-dark me-2">
              <%= experience.started_at.year %>
              <%= "- #{experience.ended_at.year}" if experience.ended_at.present? && experience.ended_at.year > experience.started_at.year %>
            </div>
            <span class="fw-bold me-2"><%= experience.place %></span>
            <span><%= experience.title %></span>
          </div>
          <div>
            <i class="fa-solid fa-chevron-right fa-fw"></i>
          </div>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="container">
  <h1>New experience</h1>
  <%= render "form", experience: @experience %>
</div>

app/views/experiences/show.html.erb
<%= turbo_stream_from @experience %>
<div class="container">
  <%= render @experience %>
  <%= turbo_stream_from "#{dom_id(@experience)}_ai_messages" %>
  <div id="<%= dom_id(@experience) %>_ai_messages">
    <%= render @experience.ai_messages.default_order %>
  </div>
  <%= turbo_frame_tag "new_ai_message", src: new_experience_ai_message_path(@experience), target: :_top %>
</div>