config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.has_role? :admin } do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_scope :user do
    get "/omniauth_callbacks/linkedin" => "omniauth_callbacks"
  end

  resources :job_listings
  resources :experiences do
    resources :ai_messages
  end

  get 'omniauth_callbacks/linkedin'

  root "application#root"
end

app/models/job_listing.rb
class JobListing < ApplicationRecord
  has_paper_trail skip: [:created_at, :updated_at]
  belongs_to :user
  has_many :experiences, dependent: :nullify

  enum job_type: {
    full_time: "full time",
    part_time: "part time",
    contract: "contract"
  }

  enum application_status: {
    open: "open",
    sent: "sent",
    interviewing: "interviewing",
    offer: "offer",
    rejected: "rejected",
    closed: "closed"
  }

  has_rich_text :description

  validates :title, presence: true
  validates :employer, presence: true

  scope :default_order, -> { order(created_at: :desc) }

  def prompt
    <<~TEXT
      The applicant is applying to this job.
      ```html
      #{title} at #{employer}
      #{description}
      ```
    TEXT
  end

  def to_s
    "#{title} at #{employer}"
  end
end

app/controllers/job_listings_controller.rb
class JobListingsController < ApplicationController
  before_action :set_job_listing, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /job_listings or /job_listings.json
  def index
    @breadcrumbs = [
      {content: "Job Listings", href: job_listings_path},
    ]
    @job_listings = current_user.job_listings.all.default_order
  end

  # GET /job_listings/1 or /job_listings/1.json
  def show
    @breadcrumbs = [
      {content: "Job Listings", href: job_listings_path},
      {content: @job_listing.to_s}
    ]
  end

  # GET /job_listings/new
  def new
    @breadcrumbs = [
      {content: "Job Listings", href: job_listings_path},
      {content: "New"}
    ]
    @job_listing = JobListing.new
  end

  # GET /job_listings/1/edit
  def edit
    @breadcrumbs = [
      {content: "Job Listings", href: job_listings_path},
      {content: @job_listing.to_s, href: job_listing_path(@job_listing)},
      {content: "Edit"}
    ]
  end

  # POST /job_listings or /job_listings.json
  def create
    @job_listing = current_user.job_listings.new(job_listing_params)

    respond_to do |format|
      if @job_listing.save
        format.html { redirect_to job_listing_url(@job_listing), notice: "Job listing was successfully created." }
        format.json { render :show, status: :created, location: @job_listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_listings/1 or /job_listings/1.json
  def update
    respond_to do |format|
      if @job_listing.update(job_listing_params)
        format.html { redirect_to job_listing_url(@job_listing), notice: "Job listing was successfully updated." }
        format.json { render :show, status: :ok, location: @job_listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_listings/1 or /job_listings/1.json
  def destroy
    @job_listing.destroy

    respond_to do |format|
      format.html { redirect_to job_listings_url, notice: "Job listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_listing
      @job_listing = current_user.job_listings.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_listing_params
      params.require(:job_listing).permit(:user_id, :title, :employer, :location, :job_type, :description, :external_url, :application_status)
    end
end

app/helpers/job_listings_helper.rb
module JobListingsHelper
  def application_status_color(job_listing)
    case job_listing.application_status.to_sym
    when :open
      "info"
    when :sent
      "primary"
    when :interviewing
      "warning"
    when :offer
      "success"
    when :rejected
      "danger"
    when :closed
      "secondary"
    else
      "secondary"
    end
  end
end

app/views/job_listings/_form.html.erb
<%= form_with(model: job_listing) do |form| %>
  <% if job_listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_listing.errors.count, "error") %> prohibited this job_listing from being saved:</h2>

      <ul>
        <% job_listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :external_url, class: "form-label" %>
    <%= form.url_field :external_url, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :employer, class: "form-label" %>
    <%= form.text_field :employer, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :location, class: "form-label" %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :job_type %>
    <%= form.select :job_type, JobListing.job_types.collect{ |k, v| [v.titleize, k]}, {}, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :application_status %>
    <%= form.select :application_status, JobListing.application_statuses.collect{ |k, v| [v.titleize, k]}, {}, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.rich_text_area :description, class: "form-control", id: "job-listing-description-rich-text-area" %>
  </div>

  <div class="my-3">
    <%= form.submit "Save", class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/job_listings/_job_listing.html.erb
<div id="<%= dom_id job_listing %>" class="card">
  <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
      <h1 class="me-auto mb-0 h6"><%= @job_listing.employer %></h1>
      <%= link_to edit_job_listing_path(@job_listing), class: "me-2" do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
      <%= button_to @job_listing, method: :delete, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure? This is NOT reversible" }, class: "btn btn-link" do %>
        <i class="fa-solid fa-trash text-danger"></i>
      <% end %>
    </div>
  </div>
  <div class="card-body">
    <p><%= job_listing.title %></p>

    <p>
      <%= JobListing.job_types.dig(job_listing.job_type).titleize %>
    </p>

    <p>
      <%= job_listing.location %>
    </p>

    <% if job_listing.external_url.present? %>
      <%= link_to "Source", job_listing.external_url, target: "_blank" %>
    <% end %>

    <hr/>

    <p>
      <%= job_listing.description %>
    </p>
  </div>
  <div class="card-footer">
    <%= content_tag :span, class: "badge text-bg-#{application_status_color(job_listing)}" do %>
      <%= job_listing.application_status %>
    <% end %>
  </div>
</div>

app/views/job_listings/edit.html.erb
<div class="container">
  <h1>Editing job listing</h1>
  <%= render "form", job_listing: @job_listing %>
</div>

app/views/job_listings/index.html.erb
<div class="container">
  <div class="card">
    <div class="card-header d-flex align-items-center">
      <h1 class="me-auto h6 mb-0">Job Listings</h1>
      <%= link_to new_job_listing_path do %>
        <i class="fa-solid fa-plus fa-lg"></i>
      <% end %>
    </div>
    <ul id="job_listings" class="list-group list-group-flush">
      <% @job_listings.each do |job_listing| %>
        <%= link_to job_listing, class: "list-group-item d-flex align-items-center" do %>
          <div class="me-auto">
            <%= content_tag :span, class: "badge text-bg-#{application_status_color(job_listing)} me-2" do %>
              <%= job_listing.application_status %>
            <% end %>
            <span class="fw-bold me-2"><%= job_listing.employer %></span>
            <span><%= job_listing.title %></span>
          </div>
          <div>
            <i class="fa-solid fa-chevron-right fa-fw"></i>
          </div>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/job_listings/new.html.erb
<div class="container">
  <h1>New job listing</h1>
  <%= render "form", job_listing: @job_listing %>
</div>

app/views/job_listings/show.html.erb
<div class="container">
  <%= render @job_listing %>
</div>